spring:
  application:
    name: Smart_Car_Pooling
  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      host: ${REDIS_HOST:happy-hippo-158333.upstash.io}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:gQAAAAAAAmp9AAIgcDE5MGE1YjAwNmE2N2M0YjRhODJlMTMwMTBhYzk2MTZjZA}
      ssl:
        enabled: true
      timeout: 2000ms
    cache:
      type: redis

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

server:
  port: ${PORT:8080}